// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/J-Y-Zhang/light-cloud-disk/app/user/internal/biz"
	"github.com/J-Y-Zhang/light-cloud-disk/app/user/internal/conf"
	"github.com/J-Y-Zhang/light-cloud-disk/app/user/internal/data"
	"github.com/J-Y-Zhang/light-cloud-disk/app/user/internal/server"
	"github.com/J-Y-Zhang/light-cloud-disk/app/user/internal/service"
	"github.com/go-kratos/kratos/contrib/registry/consul/v2"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, registry *consul.Registry) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	app := newApp(logger, grpcServer, registry)
	return app, func() {
		cleanup()
	}, nil
}
