// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/J-Y-Zhang/light-cloud-disk/api/user/v1"
	"github.com/J-Y-Zhang/light-cloud-disk/app/file/internal/biz"
	"github.com/J-Y-Zhang/light-cloud-disk/app/file/internal/conf"
	"github.com/J-Y-Zhang/light-cloud-disk/app/file/internal/data"
	"github.com/J-Y-Zhang/light-cloud-disk/app/file/internal/server"
	"github.com/J-Y-Zhang/light-cloud-disk/app/file/internal/service"
	"github.com/go-kratos/kratos/contrib/registry/consul/v2"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, upload *conf.Upload, storage *conf.Storage, logger log.Logger, registry *consul.Registry, userServiceClient v1.UserServiceClient) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	fileRepo := data.NewFileRepo(dataData, logger)
	userClient := data.NewUserClient(userServiceClient, logger)
	objectStorage, err := data.NewSeaweedFSClient(storage, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cloudStorage, err := data.NewOSSClient(storage, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	messageProducer, cleanup2, err := data.NewMessageProducer(confData, storage, fileRepo, objectStorage, cloudStorage, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	storageConfig := provideStorageConfig(storage)
	string2 := provideStoreDir(upload)
	fileUsecase := biz.NewFileUsecase(fileRepo, userClient, messageProducer, objectStorage, cloudStorage, storageConfig, string2, logger)
	fileService := service.NewFileService(fileUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, fileService, logger)
	app := newApp(logger, grpcServer, registry)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
