// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: file/v1/file.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 秒传/断点续传检查
type CheckUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileMd5       string                 `protobuf:"bytes,1,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUploadRequest) Reset() {
	*x = CheckUploadRequest{}
	mi := &file_file_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUploadRequest) ProtoMessage() {}

func (x *CheckUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUploadRequest.ProtoReflect.Descriptor instead.
func (*CheckUploadRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *CheckUploadRequest) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *CheckUploadRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CheckUploadRequest) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type CheckUploadReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CanFastUpload  bool                   `protobuf:"varint,1,opt,name=can_fast_upload,json=canFastUpload,proto3" json:"can_fast_upload,omitempty"`
	UploadedChunks []int32                `protobuf:"varint,2,rep,packed,name=uploaded_chunks,json=uploadedChunks,proto3" json:"uploaded_chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckUploadReply) Reset() {
	*x = CheckUploadReply{}
	mi := &file_file_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUploadReply) ProtoMessage() {}

func (x *CheckUploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUploadReply.ProtoReflect.Descriptor instead.
func (*CheckUploadReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{1}
}

func (x *CheckUploadReply) GetCanFastUpload() bool {
	if x != nil {
		return x.CanFastUpload
	}
	return false
}

func (x *CheckUploadReply) GetUploadedChunks() []int32 {
	if x != nil {
		return x.UploadedChunks
	}
	return nil
}

// 分块上传
type UploadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileMd5       string                 `protobuf:"bytes,1,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	ChunkSize     int32                  `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkData     []byte                 `protobuf:"bytes,4,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkRequest) Reset() {
	*x = UploadChunkRequest{}
	mi := &file_file_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkRequest) ProtoMessage() {}

func (x *UploadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkRequest.ProtoReflect.Descriptor instead.
func (*UploadChunkRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{2}
}

func (x *UploadChunkRequest) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *UploadChunkRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *UploadChunkRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *UploadChunkRequest) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

type UploadChunkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkReply) Reset() {
	*x = UploadChunkReply{}
	mi := &file_file_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkReply) ProtoMessage() {}

func (x *UploadChunkReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkReply.ProtoReflect.Descriptor instead.
func (*UploadChunkReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{3}
}

func (x *UploadChunkReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadChunkReply) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

// 合并分块
type MergeChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileMd5       string                 `protobuf:"bytes,4,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,6,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeChunksRequest) Reset() {
	*x = MergeChunksRequest{}
	mi := &file_file_v1_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeChunksRequest) ProtoMessage() {}

func (x *MergeChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeChunksRequest.ProtoReflect.Descriptor instead.
func (*MergeChunksRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{4}
}

func (x *MergeChunksRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MergeChunksRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *MergeChunksRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MergeChunksRequest) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *MergeChunksRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MergeChunksRequest) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type MergeChunksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	File          *FileInfo              `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeChunksReply) Reset() {
	*x = MergeChunksReply{}
	mi := &file_file_v1_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeChunksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeChunksReply) ProtoMessage() {}

func (x *MergeChunksReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeChunksReply.ProtoReflect.Descriptor instead.
func (*MergeChunksReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{5}
}

func (x *MergeChunksReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MergeChunksReply) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

// 文件列表
type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_file_v1_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{6}
}

func (x *ListFilesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFilesRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ListFilesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFilesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListFilesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesReply) Reset() {
	*x = ListFilesReply{}
	mi := &file_file_v1_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesReply) ProtoMessage() {}

func (x *ListFilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesReply.ProtoReflect.Descriptor instead.
func (*ListFilesReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{7}
}

func (x *ListFilesReply) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 文件信息
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FileMd5       string                 `protobuf:"bytes,3,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	IsFolder      bool                   `protobuf:"varint,5,opt,name=is_folder,json=isFolder,proto3" json:"is_folder,omitempty"`
	ParentId      int64                  `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_file_v1_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{8}
}

func (x *FileInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetIsFolder() bool {
	if x != nil {
		return x.IsFolder
	}
	return false
}

func (x *FileInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FileInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 下载
type GetDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        int64                  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLRequest) Reset() {
	*x = GetDownloadURLRequest{}
	mi := &file_file_v1_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLRequest) ProtoMessage() {}

func (x *GetDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{9}
}

func (x *GetDownloadURLRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetDownloadURLRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type GetDownloadURLReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLReply) Reset() {
	*x = GetDownloadURLReply{}
	mi := &file_file_v1_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLReply) ProtoMessage() {}

func (x *GetDownloadURLReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLReply.ProtoReflect.Descriptor instead.
func (*GetDownloadURLReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{10}
}

func (x *GetDownloadURLReply) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *GetDownloadURLReply) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// 删除文件
type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileIds       []int64                `protobuf:"varint,2,rep,packed,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_file_v1_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteFileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteFileRequest) GetFileIds() []int64 {
	if x != nil {
		return x.FileIds
	}
	return nil
}

type DeleteFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileReply) Reset() {
	*x = DeleteFileReply{}
	mi := &file_file_v1_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileReply) ProtoMessage() {}

func (x *DeleteFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileReply.ProtoReflect.Descriptor instead.
func (*DeleteFileReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteFileReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 重命名
type RenameFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        int64                  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	NewName       string                 `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileRequest) Reset() {
	*x = RenameFileRequest{}
	mi := &file_file_v1_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileRequest) ProtoMessage() {}

func (x *RenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileRequest.ProtoReflect.Descriptor instead.
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{13}
}

func (x *RenameFileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RenameFileRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *RenameFileRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileReply) Reset() {
	*x = RenameFileReply{}
	mi := &file_file_v1_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileReply) ProtoMessage() {}

func (x *RenameFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileReply.ProtoReflect.Descriptor instead.
func (*RenameFileReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{14}
}

func (x *RenameFileReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 创建文件夹
type CreateFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderRequest) Reset() {
	*x = CreateFolderRequest{}
	mi := &file_file_v1_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderRequest) ProtoMessage() {}

func (x *CreateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderRequest.ProtoReflect.Descriptor instead.
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{15}
}

func (x *CreateFolderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateFolderRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateFolderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFolderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Folder        *FileInfo              `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderReply) Reset() {
	*x = CreateFolderReply{}
	mi := &file_file_v1_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderReply) ProtoMessage() {}

func (x *CreateFolderReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderReply.ProtoReflect.Descriptor instead.
func (*CreateFolderReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{16}
}

func (x *CreateFolderReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateFolderReply) GetFolder() *FileInfo {
	if x != nil {
		return x.Folder
	}
	return nil
}

// 移动文件
type MoveFileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileIds        []int64                `protobuf:"varint,2,rep,packed,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	TargetFolderId int64                  `protobuf:"varint,3,opt,name=target_folder_id,json=targetFolderId,proto3" json:"target_folder_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MoveFileRequest) Reset() {
	*x = MoveFileRequest{}
	mi := &file_file_v1_file_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFileRequest) ProtoMessage() {}

func (x *MoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFileRequest.ProtoReflect.Descriptor instead.
func (*MoveFileRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{17}
}

func (x *MoveFileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MoveFileRequest) GetFileIds() []int64 {
	if x != nil {
		return x.FileIds
	}
	return nil
}

func (x *MoveFileRequest) GetTargetFolderId() int64 {
	if x != nil {
		return x.TargetFolderId
	}
	return 0
}

type MoveFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveFileReply) Reset() {
	*x = MoveFileReply{}
	mi := &file_file_v1_file_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFileReply) ProtoMessage() {}

func (x *MoveFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFileReply.ProtoReflect.Descriptor instead.
func (*MoveFileReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{18}
}

func (x *MoveFileReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 回收站列表
type ListTrashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrashRequest) Reset() {
	*x = ListTrashRequest{}
	mi := &file_file_v1_file_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrashRequest) ProtoMessage() {}

func (x *ListTrashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrashRequest.ProtoReflect.Descriptor instead.
func (*ListTrashRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{19}
}

func (x *ListTrashRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListTrashRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTrashRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTrashReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*TrashFileInfo       `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrashReply) Reset() {
	*x = ListTrashReply{}
	mi := &file_file_v1_file_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrashReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrashReply) ProtoMessage() {}

func (x *ListTrashReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrashReply.ProtoReflect.Descriptor instead.
func (*ListTrashReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{20}
}

func (x *ListTrashReply) GetFiles() []*TrashFileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListTrashReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TrashFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	IsFolder      bool                   `protobuf:"varint,4,opt,name=is_folder,json=isFolder,proto3" json:"is_folder,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashFileInfo) Reset() {
	*x = TrashFileInfo{}
	mi := &file_file_v1_file_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashFileInfo) ProtoMessage() {}

func (x *TrashFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashFileInfo.ProtoReflect.Descriptor instead.
func (*TrashFileInfo) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{21}
}

func (x *TrashFileInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TrashFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrashFileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TrashFileInfo) GetIsFolder() bool {
	if x != nil {
		return x.IsFolder
	}
	return false
}

func (x *TrashFileInfo) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *TrashFileInfo) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

// 恢复文件
type RestoreFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileIds       []int64                `protobuf:"varint,2,rep,packed,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFileRequest) Reset() {
	*x = RestoreFileRequest{}
	mi := &file_file_v1_file_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFileRequest) ProtoMessage() {}

func (x *RestoreFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFileRequest.ProtoReflect.Descriptor instead.
func (*RestoreFileRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{22}
}

func (x *RestoreFileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RestoreFileRequest) GetFileIds() []int64 {
	if x != nil {
		return x.FileIds
	}
	return nil
}

type RestoreFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFileReply) Reset() {
	*x = RestoreFileReply{}
	mi := &file_file_v1_file_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFileReply) ProtoMessage() {}

func (x *RestoreFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFileReply.ProtoReflect.Descriptor instead.
func (*RestoreFileReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{23}
}

func (x *RestoreFileReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 彻底删除
type PermanentDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileIds       []int64                `protobuf:"varint,2,rep,packed,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermanentDeleteRequest) Reset() {
	*x = PermanentDeleteRequest{}
	mi := &file_file_v1_file_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermanentDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermanentDeleteRequest) ProtoMessage() {}

func (x *PermanentDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermanentDeleteRequest.ProtoReflect.Descriptor instead.
func (*PermanentDeleteRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{24}
}

func (x *PermanentDeleteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PermanentDeleteRequest) GetFileIds() []int64 {
	if x != nil {
		return x.FileIds
	}
	return nil
}

type PermanentDeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermanentDeleteReply) Reset() {
	*x = PermanentDeleteReply{}
	mi := &file_file_v1_file_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermanentDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermanentDeleteReply) ProtoMessage() {}

func (x *PermanentDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermanentDeleteReply.ProtoReflect.Descriptor instead.
func (*PermanentDeleteReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{25}
}

func (x *PermanentDeleteReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 分享
type CreateShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        int64                  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ExpireDays    int32                  `protobuf:"varint,3,opt,name=expire_days,json=expireDays,proto3" json:"expire_days,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareRequest) Reset() {
	*x = CreateShareRequest{}
	mi := &file_file_v1_file_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareRequest) ProtoMessage() {}

func (x *CreateShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareRequest.ProtoReflect.Descriptor instead.
func (*CreateShareRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{26}
}

func (x *CreateShareRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateShareRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *CreateShareRequest) GetExpireDays() int32 {
	if x != nil {
		return x.ExpireDays
	}
	return 0
}

func (x *CreateShareRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateShareReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareId       string                 `protobuf:"bytes,1,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"`
	ShareUrl      string                 `protobuf:"bytes,2,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareReply) Reset() {
	*x = CreateShareReply{}
	mi := &file_file_v1_file_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareReply) ProtoMessage() {}

func (x *CreateShareReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareReply.ProtoReflect.Descriptor instead.
func (*CreateShareReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{27}
}

func (x *CreateShareReply) GetShareId() string {
	if x != nil {
		return x.ShareId
	}
	return ""
}

func (x *CreateShareReply) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

func (x *CreateShareReply) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateShareReply) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type GetShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareId       string                 `protobuf:"bytes,1,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareRequest) Reset() {
	*x = GetShareRequest{}
	mi := &file_file_v1_file_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareRequest) ProtoMessage() {}

func (x *GetShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareRequest.ProtoReflect.Descriptor instead.
func (*GetShareRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{28}
}

func (x *GetShareRequest) GetShareId() string {
	if x != nil {
		return x.ShareId
	}
	return ""
}

func (x *GetShareRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetShareReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareReply) Reset() {
	*x = GetShareReply{}
	mi := &file_file_v1_file_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareReply) ProtoMessage() {}

func (x *GetShareReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareReply.ProtoReflect.Descriptor instead.
func (*GetShareReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{29}
}

func (x *GetShareReply) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *GetShareReply) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

// 搜索
type SearchFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilesRequest) Reset() {
	*x = SearchFilesRequest{}
	mi := &file_file_v1_file_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilesRequest) ProtoMessage() {}

func (x *SearchFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilesRequest.ProtoReflect.Descriptor instead.
func (*SearchFilesRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{30}
}

func (x *SearchFilesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchFilesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchFilesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchFilesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchFilesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilesReply) Reset() {
	*x = SearchFilesReply{}
	mi := &file_file_v1_file_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilesReply) ProtoMessage() {}

func (x *SearchFilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilesReply.ProtoReflect.Descriptor instead.
func (*SearchFilesReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{31}
}

func (x *SearchFilesReply) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SearchFilesReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_file_v1_file_proto protoreflect.FileDescriptor

const file_file_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x12file/v1/file.proto\x12\vapi.file.v1\"o\n" +
	"\x12CheckUploadRequest\x12\x19\n" +
	"\bfile_md5\x18\x01 \x01(\tR\afileMd5\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\"c\n" +
	"\x10CheckUploadReply\x12&\n" +
	"\x0fcan_fast_upload\x18\x01 \x01(\bR\rcanFastUpload\x12'\n" +
	"\x0fuploaded_chunks\x18\x02 \x03(\x05R\x0euploadedChunks\"\x8e\x01\n" +
	"\x12UploadChunkRequest\x12\x19\n" +
	"\bfile_md5\x18\x01 \x01(\tR\afileMd5\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x05R\tchunkSize\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x04 \x01(\fR\tchunkData\"M\n" +
	"\x10UploadChunkReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\"\xc2\x01\n" +
	"\x12MergeChunksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x19\n" +
	"\bfile_md5\x18\x04 \x01(\tR\afileMd5\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x12!\n" +
	"\ftotal_chunks\x18\x06 \x01(\x05R\vtotalChunks\"W\n" +
	"\x10MergeChunksReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x04file\x18\x02 \x01(\v2\x15.api.file.v1.FileInfoR\x04file\"y\n" +
	"\x10ListFilesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"S\n" +
	"\x0eListFilesReply\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.api.file.v1.FileInfoR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xe9\x01\n" +
	"\bFileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bfile_md5\x18\x03 \x01(\tR\afileMd5\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1b\n" +
	"\tis_folder\x18\x05 \x01(\bR\bisFolder\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"I\n" +
	"\x15GetDownloadURLRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\x03R\x06fileId\"U\n" +
	"\x13GetDownloadURLReply\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"G\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bfile_ids\x18\x02 \x03(\x03R\afileIds\"+\n" +
	"\x0fDeleteFileReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"`\n" +
	"\x11RenameFileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\x03R\x06fileId\x12\x19\n" +
	"\bnew_name\x18\x03 \x01(\tR\anewName\"+\n" +
	"\x0fRenameFileReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"_\n" +
	"\x13CreateFolderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\\\n" +
	"\x11CreateFolderReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x06folder\x18\x02 \x01(\v2\x15.api.file.v1.FileInfoR\x06folder\"o\n" +
	"\x0fMoveFileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bfile_ids\x18\x02 \x03(\x03R\afileIds\x12(\n" +
	"\x10target_folder_id\x18\x03 \x01(\x03R\x0etargetFolderId\")\n" +
	"\rMoveFileReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\x10ListTrashRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"X\n" +
	"\x0eListTrashReply\x120\n" +
	"\x05files\x18\x01 \x03(\v2\x1a.api.file.v1.TrashFileInfoR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa0\x01\n" +
	"\rTrashFileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1b\n" +
	"\tis_folder\x18\x04 \x01(\bR\bisFolder\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\x03R\tdeletedAt\x12\x1b\n" +
	"\texpire_at\x18\x06 \x01(\x03R\bexpireAt\"H\n" +
	"\x12RestoreFileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bfile_ids\x18\x02 \x03(\x03R\afileIds\",\n" +
	"\x10RestoreFileReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x16PermanentDeleteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bfile_ids\x18\x02 \x03(\x03R\afileIds\"0\n" +
	"\x14PermanentDeleteReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x83\x01\n" +
	"\x12CreateShareRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\x03R\x06fileId\x12\x1f\n" +
	"\vexpire_days\x18\x03 \x01(\x05R\n" +
	"expireDays\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x83\x01\n" +
	"\x10CreateShareReply\x12\x19\n" +
	"\bshare_id\x18\x01 \x01(\tR\ashareId\x12\x1b\n" +
	"\tshare_url\x18\x02 \x01(\tR\bshareUrl\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\x03R\bexpireAt\"H\n" +
	"\x0fGetShareRequest\x12\x19\n" +
	"\bshare_id\x18\x01 \x01(\tR\ashareId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"]\n" +
	"\rGetShareReply\x12)\n" +
	"\x04file\x18\x01 \x01(\v2\x15.api.file.v1.FileInfoR\x04file\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\"x\n" +
	"\x12SearchFilesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"U\n" +
	"\x10SearchFilesReply\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.api.file.v1.FileInfoR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xa2\t\n" +
	"\vFileService\x12M\n" +
	"\vCheckUpload\x12\x1f.api.file.v1.CheckUploadRequest\x1a\x1d.api.file.v1.CheckUploadReply\x12M\n" +
	"\vUploadChunk\x12\x1f.api.file.v1.UploadChunkRequest\x1a\x1d.api.file.v1.UploadChunkReply\x12M\n" +
	"\vMergeChunks\x12\x1f.api.file.v1.MergeChunksRequest\x1a\x1d.api.file.v1.MergeChunksReply\x12G\n" +
	"\tListFiles\x12\x1d.api.file.v1.ListFilesRequest\x1a\x1b.api.file.v1.ListFilesReply\x12V\n" +
	"\x0eGetDownloadURL\x12\".api.file.v1.GetDownloadURLRequest\x1a .api.file.v1.GetDownloadURLReply\x12J\n" +
	"\n" +
	"DeleteFile\x12\x1e.api.file.v1.DeleteFileRequest\x1a\x1c.api.file.v1.DeleteFileReply\x12J\n" +
	"\n" +
	"RenameFile\x12\x1e.api.file.v1.RenameFileRequest\x1a\x1c.api.file.v1.RenameFileReply\x12P\n" +
	"\fCreateFolder\x12 .api.file.v1.CreateFolderRequest\x1a\x1e.api.file.v1.CreateFolderReply\x12D\n" +
	"\bMoveFile\x12\x1c.api.file.v1.MoveFileRequest\x1a\x1a.api.file.v1.MoveFileReply\x12G\n" +
	"\tListTrash\x12\x1d.api.file.v1.ListTrashRequest\x1a\x1b.api.file.v1.ListTrashReply\x12M\n" +
	"\vRestoreFile\x12\x1f.api.file.v1.RestoreFileRequest\x1a\x1d.api.file.v1.RestoreFileReply\x12Y\n" +
	"\x0fPermanentDelete\x12#.api.file.v1.PermanentDeleteRequest\x1a!.api.file.v1.PermanentDeleteReply\x12M\n" +
	"\vCreateShare\x12\x1f.api.file.v1.CreateShareRequest\x1a\x1d.api.file.v1.CreateShareReply\x12D\n" +
	"\bGetShare\x12\x1c.api.file.v1.GetShareRequest\x1a\x1a.api.file.v1.GetShareReply\x12M\n" +
	"\vSearchFiles\x12\x1f.api.file.v1.SearchFilesRequest\x1a\x1d.api.file.v1.SearchFilesReplyB6Z4github.com/J-Y-Zhang/light-cloud-disk/api/file/v1;v1b\x06proto3"

var (
	file_file_v1_file_proto_rawDescOnce sync.Once
	file_file_v1_file_proto_rawDescData []byte
)

func file_file_v1_file_proto_rawDescGZIP() []byte {
	file_file_v1_file_proto_rawDescOnce.Do(func() {
		file_file_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_v1_file_proto_rawDesc), len(file_file_v1_file_proto_rawDesc)))
	})
	return file_file_v1_file_proto_rawDescData
}

var file_file_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_file_v1_file_proto_goTypes = []any{
	(*CheckUploadRequest)(nil),     // 0: api.file.v1.CheckUploadRequest
	(*CheckUploadReply)(nil),       // 1: api.file.v1.CheckUploadReply
	(*UploadChunkRequest)(nil),     // 2: api.file.v1.UploadChunkRequest
	(*UploadChunkReply)(nil),       // 3: api.file.v1.UploadChunkReply
	(*MergeChunksRequest)(nil),     // 4: api.file.v1.MergeChunksRequest
	(*MergeChunksReply)(nil),       // 5: api.file.v1.MergeChunksReply
	(*ListFilesRequest)(nil),       // 6: api.file.v1.ListFilesRequest
	(*ListFilesReply)(nil),         // 7: api.file.v1.ListFilesReply
	(*FileInfo)(nil),               // 8: api.file.v1.FileInfo
	(*GetDownloadURLRequest)(nil),  // 9: api.file.v1.GetDownloadURLRequest
	(*GetDownloadURLReply)(nil),    // 10: api.file.v1.GetDownloadURLReply
	(*DeleteFileRequest)(nil),      // 11: api.file.v1.DeleteFileRequest
	(*DeleteFileReply)(nil),        // 12: api.file.v1.DeleteFileReply
	(*RenameFileRequest)(nil),      // 13: api.file.v1.RenameFileRequest
	(*RenameFileReply)(nil),        // 14: api.file.v1.RenameFileReply
	(*CreateFolderRequest)(nil),    // 15: api.file.v1.CreateFolderRequest
	(*CreateFolderReply)(nil),      // 16: api.file.v1.CreateFolderReply
	(*MoveFileRequest)(nil),        // 17: api.file.v1.MoveFileRequest
	(*MoveFileReply)(nil),          // 18: api.file.v1.MoveFileReply
	(*ListTrashRequest)(nil),       // 19: api.file.v1.ListTrashRequest
	(*ListTrashReply)(nil),         // 20: api.file.v1.ListTrashReply
	(*TrashFileInfo)(nil),          // 21: api.file.v1.TrashFileInfo
	(*RestoreFileRequest)(nil),     // 22: api.file.v1.RestoreFileRequest
	(*RestoreFileReply)(nil),       // 23: api.file.v1.RestoreFileReply
	(*PermanentDeleteRequest)(nil), // 24: api.file.v1.PermanentDeleteRequest
	(*PermanentDeleteReply)(nil),   // 25: api.file.v1.PermanentDeleteReply
	(*CreateShareRequest)(nil),     // 26: api.file.v1.CreateShareRequest
	(*CreateShareReply)(nil),       // 27: api.file.v1.CreateShareReply
	(*GetShareRequest)(nil),        // 28: api.file.v1.GetShareRequest
	(*GetShareReply)(nil),          // 29: api.file.v1.GetShareReply
	(*SearchFilesRequest)(nil),     // 30: api.file.v1.SearchFilesRequest
	(*SearchFilesReply)(nil),       // 31: api.file.v1.SearchFilesReply
}
var file_file_v1_file_proto_depIdxs = []int32{
	8,  // 0: api.file.v1.MergeChunksReply.file:type_name -> api.file.v1.FileInfo
	8,  // 1: api.file.v1.ListFilesReply.files:type_name -> api.file.v1.FileInfo
	8,  // 2: api.file.v1.CreateFolderReply.folder:type_name -> api.file.v1.FileInfo
	21, // 3: api.file.v1.ListTrashReply.files:type_name -> api.file.v1.TrashFileInfo
	8,  // 4: api.file.v1.GetShareReply.file:type_name -> api.file.v1.FileInfo
	8,  // 5: api.file.v1.SearchFilesReply.files:type_name -> api.file.v1.FileInfo
	0,  // 6: api.file.v1.FileService.CheckUpload:input_type -> api.file.v1.CheckUploadRequest
	2,  // 7: api.file.v1.FileService.UploadChunk:input_type -> api.file.v1.UploadChunkRequest
	4,  // 8: api.file.v1.FileService.MergeChunks:input_type -> api.file.v1.MergeChunksRequest
	6,  // 9: api.file.v1.FileService.ListFiles:input_type -> api.file.v1.ListFilesRequest
	9,  // 10: api.file.v1.FileService.GetDownloadURL:input_type -> api.file.v1.GetDownloadURLRequest
	11, // 11: api.file.v1.FileService.DeleteFile:input_type -> api.file.v1.DeleteFileRequest
	13, // 12: api.file.v1.FileService.RenameFile:input_type -> api.file.v1.RenameFileRequest
	15, // 13: api.file.v1.FileService.CreateFolder:input_type -> api.file.v1.CreateFolderRequest
	17, // 14: api.file.v1.FileService.MoveFile:input_type -> api.file.v1.MoveFileRequest
	19, // 15: api.file.v1.FileService.ListTrash:input_type -> api.file.v1.ListTrashRequest
	22, // 16: api.file.v1.FileService.RestoreFile:input_type -> api.file.v1.RestoreFileRequest
	24, // 17: api.file.v1.FileService.PermanentDelete:input_type -> api.file.v1.PermanentDeleteRequest
	26, // 18: api.file.v1.FileService.CreateShare:input_type -> api.file.v1.CreateShareRequest
	28, // 19: api.file.v1.FileService.GetShare:input_type -> api.file.v1.GetShareRequest
	30, // 20: api.file.v1.FileService.SearchFiles:input_type -> api.file.v1.SearchFilesRequest
	1,  // 21: api.file.v1.FileService.CheckUpload:output_type -> api.file.v1.CheckUploadReply
	3,  // 22: api.file.v1.FileService.UploadChunk:output_type -> api.file.v1.UploadChunkReply
	5,  // 23: api.file.v1.FileService.MergeChunks:output_type -> api.file.v1.MergeChunksReply
	7,  // 24: api.file.v1.FileService.ListFiles:output_type -> api.file.v1.ListFilesReply
	10, // 25: api.file.v1.FileService.GetDownloadURL:output_type -> api.file.v1.GetDownloadURLReply
	12, // 26: api.file.v1.FileService.DeleteFile:output_type -> api.file.v1.DeleteFileReply
	14, // 27: api.file.v1.FileService.RenameFile:output_type -> api.file.v1.RenameFileReply
	16, // 28: api.file.v1.FileService.CreateFolder:output_type -> api.file.v1.CreateFolderReply
	18, // 29: api.file.v1.FileService.MoveFile:output_type -> api.file.v1.MoveFileReply
	20, // 30: api.file.v1.FileService.ListTrash:output_type -> api.file.v1.ListTrashReply
	23, // 31: api.file.v1.FileService.RestoreFile:output_type -> api.file.v1.RestoreFileReply
	25, // 32: api.file.v1.FileService.PermanentDelete:output_type -> api.file.v1.PermanentDeleteReply
	27, // 33: api.file.v1.FileService.CreateShare:output_type -> api.file.v1.CreateShareReply
	29, // 34: api.file.v1.FileService.GetShare:output_type -> api.file.v1.GetShareReply
	31, // 35: api.file.v1.FileService.SearchFiles:output_type -> api.file.v1.SearchFilesReply
	21, // [21:36] is the sub-list for method output_type
	6,  // [6:21] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_file_v1_file_proto_init() }
func file_file_v1_file_proto_init() {
	if File_file_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_v1_file_proto_rawDesc), len(file_file_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_v1_file_proto_goTypes,
		DependencyIndexes: file_file_v1_file_proto_depIdxs,
		MessageInfos:      file_file_v1_file_proto_msgTypes,
	}.Build()
	File_file_v1_file_proto = out.File
	file_file_v1_file_proto_goTypes = nil
	file_file_v1_file_proto_depIdxs = nil
}
