// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: file/v1/file.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFileServiceCheckUpload = "/api.file.v1.FileService/CheckUpload"
const OperationFileServiceCreateFolder = "/api.file.v1.FileService/CreateFolder"
const OperationFileServiceCreateShare = "/api.file.v1.FileService/CreateShare"
const OperationFileServiceDeleteFile = "/api.file.v1.FileService/DeleteFile"
const OperationFileServiceGetDownloadURL = "/api.file.v1.FileService/GetDownloadURL"
const OperationFileServiceGetShare = "/api.file.v1.FileService/GetShare"
const OperationFileServiceListFiles = "/api.file.v1.FileService/ListFiles"
const OperationFileServiceListTrash = "/api.file.v1.FileService/ListTrash"
const OperationFileServiceMergeChunks = "/api.file.v1.FileService/MergeChunks"
const OperationFileServiceMoveFile = "/api.file.v1.FileService/MoveFile"
const OperationFileServicePermanentDelete = "/api.file.v1.FileService/PermanentDelete"
const OperationFileServiceRenameFile = "/api.file.v1.FileService/RenameFile"
const OperationFileServiceRestoreFile = "/api.file.v1.FileService/RestoreFile"
const OperationFileServiceSearchFiles = "/api.file.v1.FileService/SearchFiles"
const OperationFileServiceUploadChunk = "/api.file.v1.FileService/UploadChunk"

type FileServiceHTTPServer interface {
	// CheckUpload 检查秒传和断点续传
	CheckUpload(context.Context, *CheckUploadRequest) (*CheckUploadReply, error)
	// CreateFolder 创建文件夹
	CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderReply, error)
	// CreateShare 创建分享链接
	CreateShare(context.Context, *CreateShareRequest) (*CreateShareReply, error)
	// DeleteFile 删除文件（移到回收站）
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileReply, error)
	// GetDownloadURL 获取文件下载链接
	GetDownloadURL(context.Context, *GetDownloadURLRequest) (*GetDownloadURLReply, error)
	// GetShare 获取分享内容
	GetShare(context.Context, *GetShareRequest) (*GetShareReply, error)
	// ListFiles 获取用户文件列表
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesReply, error)
	// ListTrash 获取回收站列表
	ListTrash(context.Context, *ListTrashRequest) (*ListTrashReply, error)
	// MergeChunks 合并文件分块
	MergeChunks(context.Context, *MergeChunksRequest) (*MergeChunksReply, error)
	// MoveFile 移动文件/文件夹
	MoveFile(context.Context, *MoveFileRequest) (*MoveFileReply, error)
	// PermanentDelete 彻底删除文件
	PermanentDelete(context.Context, *PermanentDeleteRequest) (*PermanentDeleteReply, error)
	// RenameFile 重命名文件
	RenameFile(context.Context, *RenameFileRequest) (*RenameFileReply, error)
	// RestoreFile 恢复回收站文件
	RestoreFile(context.Context, *RestoreFileRequest) (*RestoreFileReply, error)
	// SearchFiles 搜索文件
	SearchFiles(context.Context, *SearchFilesRequest) (*SearchFilesReply, error)
	// UploadChunk 上传文件分块
	UploadChunk(context.Context, *UploadChunkRequest) (*UploadChunkReply, error)
}

func RegisterFileServiceHTTPServer(s *http.Server, srv FileServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/file/upload/check", _FileService_CheckUpload0_HTTP_Handler(srv))
	r.POST("/api/v1/file/upload/chunk", _FileService_UploadChunk0_HTTP_Handler(srv))
	r.POST("/api/v1/file/upload/merge", _FileService_MergeChunks0_HTTP_Handler(srv))
	r.GET("/api/v1/files", _FileService_ListFiles0_HTTP_Handler(srv))
	r.GET("/api/v1/file/download", _FileService_GetDownloadURL0_HTTP_Handler(srv))
	r.DELETE("/api/v1/file", _FileService_DeleteFile0_HTTP_Handler(srv))
	r.PUT("/api/v1/file/rename", _FileService_RenameFile0_HTTP_Handler(srv))
	r.POST("/api/v1/folder", _FileService_CreateFolder0_HTTP_Handler(srv))
	r.PUT("/api/v1/file/move", _FileService_MoveFile0_HTTP_Handler(srv))
	r.GET("/api/v1/trash", _FileService_ListTrash0_HTTP_Handler(srv))
	r.POST("/api/v1/trash/restore", _FileService_RestoreFile0_HTTP_Handler(srv))
	r.DELETE("/api/v1/trash", _FileService_PermanentDelete0_HTTP_Handler(srv))
	r.POST("/api/v1/share", _FileService_CreateShare0_HTTP_Handler(srv))
	r.GET("/api/v1/share/{share_id}", _FileService_GetShare0_HTTP_Handler(srv))
	r.GET("/api/v1/files/search", _FileService_SearchFiles0_HTTP_Handler(srv))
}

func _FileService_CheckUpload0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckUploadRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceCheckUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckUpload(ctx, req.(*CheckUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckUploadReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_UploadChunk0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadChunkRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceUploadChunk)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadChunk(ctx, req.(*UploadChunkRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadChunkReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_MergeChunks0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MergeChunksRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceMergeChunks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MergeChunks(ctx, req.(*MergeChunksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MergeChunksReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_ListFiles0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListFilesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceListFiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFiles(ctx, req.(*ListFilesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFilesReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_GetDownloadURL0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDownloadURLRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceGetDownloadURL)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDownloadURL(ctx, req.(*GetDownloadURLRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDownloadURLReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_DeleteFile0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceDeleteFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteFile(ctx, req.(*DeleteFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteFileReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_RenameFile0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RenameFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceRenameFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RenameFile(ctx, req.(*RenameFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RenameFileReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_CreateFolder0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateFolderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceCreateFolder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateFolder(ctx, req.(*CreateFolderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateFolderReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_MoveFile0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MoveFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceMoveFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MoveFile(ctx, req.(*MoveFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MoveFileReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_ListTrash0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTrashRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceListTrash)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTrash(ctx, req.(*ListTrashRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTrashReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_RestoreFile0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RestoreFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceRestoreFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RestoreFile(ctx, req.(*RestoreFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RestoreFileReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_PermanentDelete0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PermanentDeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServicePermanentDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PermanentDelete(ctx, req.(*PermanentDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PermanentDeleteReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_CreateShare0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateShareRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceCreateShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateShare(ctx, req.(*CreateShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateShareReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_GetShare0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetShareRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceGetShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetShare(ctx, req.(*GetShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetShareReply)
		return ctx.Result(200, reply)
	}
}

func _FileService_SearchFiles0_HTTP_Handler(srv FileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchFilesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileServiceSearchFiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchFiles(ctx, req.(*SearchFilesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchFilesReply)
		return ctx.Result(200, reply)
	}
}

type FileServiceHTTPClient interface {
	// CheckUpload 检查秒传和断点续传
	CheckUpload(ctx context.Context, req *CheckUploadRequest, opts ...http.CallOption) (rsp *CheckUploadReply, err error)
	// CreateFolder 创建文件夹
	CreateFolder(ctx context.Context, req *CreateFolderRequest, opts ...http.CallOption) (rsp *CreateFolderReply, err error)
	// CreateShare 创建分享链接
	CreateShare(ctx context.Context, req *CreateShareRequest, opts ...http.CallOption) (rsp *CreateShareReply, err error)
	// DeleteFile 删除文件（移到回收站）
	DeleteFile(ctx context.Context, req *DeleteFileRequest, opts ...http.CallOption) (rsp *DeleteFileReply, err error)
	// GetDownloadURL 获取文件下载链接
	GetDownloadURL(ctx context.Context, req *GetDownloadURLRequest, opts ...http.CallOption) (rsp *GetDownloadURLReply, err error)
	// GetShare 获取分享内容
	GetShare(ctx context.Context, req *GetShareRequest, opts ...http.CallOption) (rsp *GetShareReply, err error)
	// ListFiles 获取用户文件列表
	ListFiles(ctx context.Context, req *ListFilesRequest, opts ...http.CallOption) (rsp *ListFilesReply, err error)
	// ListTrash 获取回收站列表
	ListTrash(ctx context.Context, req *ListTrashRequest, opts ...http.CallOption) (rsp *ListTrashReply, err error)
	// MergeChunks 合并文件分块
	MergeChunks(ctx context.Context, req *MergeChunksRequest, opts ...http.CallOption) (rsp *MergeChunksReply, err error)
	// MoveFile 移动文件/文件夹
	MoveFile(ctx context.Context, req *MoveFileRequest, opts ...http.CallOption) (rsp *MoveFileReply, err error)
	// PermanentDelete 彻底删除文件
	PermanentDelete(ctx context.Context, req *PermanentDeleteRequest, opts ...http.CallOption) (rsp *PermanentDeleteReply, err error)
	// RenameFile 重命名文件
	RenameFile(ctx context.Context, req *RenameFileRequest, opts ...http.CallOption) (rsp *RenameFileReply, err error)
	// RestoreFile 恢复回收站文件
	RestoreFile(ctx context.Context, req *RestoreFileRequest, opts ...http.CallOption) (rsp *RestoreFileReply, err error)
	// SearchFiles 搜索文件
	SearchFiles(ctx context.Context, req *SearchFilesRequest, opts ...http.CallOption) (rsp *SearchFilesReply, err error)
	// UploadChunk 上传文件分块
	UploadChunk(ctx context.Context, req *UploadChunkRequest, opts ...http.CallOption) (rsp *UploadChunkReply, err error)
}

type FileServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewFileServiceHTTPClient(client *http.Client) FileServiceHTTPClient {
	return &FileServiceHTTPClientImpl{client}
}

// CheckUpload 检查秒传和断点续传
func (c *FileServiceHTTPClientImpl) CheckUpload(ctx context.Context, in *CheckUploadRequest, opts ...http.CallOption) (*CheckUploadReply, error) {
	var out CheckUploadReply
	pattern := "/api/v1/file/upload/check"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileServiceCheckUpload))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateFolder 创建文件夹
func (c *FileServiceHTTPClientImpl) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...http.CallOption) (*CreateFolderReply, error) {
	var out CreateFolderReply
	pattern := "/api/v1/folder"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileServiceCreateFolder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateShare 创建分享链接
func (c *FileServiceHTTPClientImpl) CreateShare(ctx context.Context, in *CreateShareRequest, opts ...http.CallOption) (*CreateShareReply, error) {
	var out CreateShareReply
	pattern := "/api/v1/share"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileServiceCreateShare))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteFile 删除文件（移到回收站）
func (c *FileServiceHTTPClientImpl) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...http.CallOption) (*DeleteFileReply, error) {
	var out DeleteFileReply
	pattern := "/api/v1/file"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileServiceDeleteFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDownloadURL 获取文件下载链接
func (c *FileServiceHTTPClientImpl) GetDownloadURL(ctx context.Context, in *GetDownloadURLRequest, opts ...http.CallOption) (*GetDownloadURLReply, error) {
	var out GetDownloadURLReply
	pattern := "/api/v1/file/download"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileServiceGetDownloadURL))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetShare 获取分享内容
func (c *FileServiceHTTPClientImpl) GetShare(ctx context.Context, in *GetShareRequest, opts ...http.CallOption) (*GetShareReply, error) {
	var out GetShareReply
	pattern := "/api/v1/share/{share_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileServiceGetShare))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListFiles 获取用户文件列表
func (c *FileServiceHTTPClientImpl) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...http.CallOption) (*ListFilesReply, error) {
	var out ListFilesReply
	pattern := "/api/v1/files"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileServiceListFiles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTrash 获取回收站列表
func (c *FileServiceHTTPClientImpl) ListTrash(ctx context.Context, in *ListTrashRequest, opts ...http.CallOption) (*ListTrashReply, error) {
	var out ListTrashReply
	pattern := "/api/v1/trash"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileServiceListTrash))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MergeChunks 合并文件分块
func (c *FileServiceHTTPClientImpl) MergeChunks(ctx context.Context, in *MergeChunksRequest, opts ...http.CallOption) (*MergeChunksReply, error) {
	var out MergeChunksReply
	pattern := "/api/v1/file/upload/merge"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileServiceMergeChunks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MoveFile 移动文件/文件夹
func (c *FileServiceHTTPClientImpl) MoveFile(ctx context.Context, in *MoveFileRequest, opts ...http.CallOption) (*MoveFileReply, error) {
	var out MoveFileReply
	pattern := "/api/v1/file/move"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileServiceMoveFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PermanentDelete 彻底删除文件
func (c *FileServiceHTTPClientImpl) PermanentDelete(ctx context.Context, in *PermanentDeleteRequest, opts ...http.CallOption) (*PermanentDeleteReply, error) {
	var out PermanentDeleteReply
	pattern := "/api/v1/trash"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileServicePermanentDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RenameFile 重命名文件
func (c *FileServiceHTTPClientImpl) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...http.CallOption) (*RenameFileReply, error) {
	var out RenameFileReply
	pattern := "/api/v1/file/rename"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileServiceRenameFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RestoreFile 恢复回收站文件
func (c *FileServiceHTTPClientImpl) RestoreFile(ctx context.Context, in *RestoreFileRequest, opts ...http.CallOption) (*RestoreFileReply, error) {
	var out RestoreFileReply
	pattern := "/api/v1/trash/restore"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileServiceRestoreFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchFiles 搜索文件
func (c *FileServiceHTTPClientImpl) SearchFiles(ctx context.Context, in *SearchFilesRequest, opts ...http.CallOption) (*SearchFilesReply, error) {
	var out SearchFilesReply
	pattern := "/api/v1/files/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileServiceSearchFiles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadChunk 上传文件分块
func (c *FileServiceHTTPClientImpl) UploadChunk(ctx context.Context, in *UploadChunkRequest, opts ...http.CallOption) (*UploadChunkReply, error) {
	var out UploadChunkReply
	pattern := "/api/v1/file/upload/chunk"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileServiceUploadChunk))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
