// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0--rc2
// source: file/v1/file.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_CheckUpload_FullMethodName             = "/api.file.v1.FileService/CheckUpload"
	FileService_UploadChunk_FullMethodName             = "/api.file.v1.FileService/UploadChunk"
	FileService_MergeChunks_FullMethodName             = "/api.file.v1.FileService/MergeChunks"
	FileService_ListFiles_FullMethodName               = "/api.file.v1.FileService/ListFiles"
	FileService_GetDownloadURL_FullMethodName          = "/api.file.v1.FileService/GetDownloadURL"
	FileService_DeleteFile_FullMethodName              = "/api.file.v1.FileService/DeleteFile"
	FileService_RenameFile_FullMethodName              = "/api.file.v1.FileService/RenameFile"
	FileService_CreateFolder_FullMethodName            = "/api.file.v1.FileService/CreateFolder"
	FileService_MoveFile_FullMethodName                = "/api.file.v1.FileService/MoveFile"
	FileService_ListTrash_FullMethodName               = "/api.file.v1.FileService/ListTrash"
	FileService_RestoreFile_FullMethodName             = "/api.file.v1.FileService/RestoreFile"
	FileService_PermanentDelete_FullMethodName         = "/api.file.v1.FileService/PermanentDelete"
	FileService_CreateShare_FullMethodName             = "/api.file.v1.FileService/CreateShare"
	FileService_GetShare_FullMethodName                = "/api.file.v1.FileService/GetShare"
	FileService_SearchFiles_FullMethodName             = "/api.file.v1.FileService/SearchFiles"
	FileService_GetDiskUsage_FullMethodName            = "/api.file.v1.FileService/GetDiskUsage"
	FileService_StreamFileContent_FullMethodName       = "/api.file.v1.FileService/StreamFileContent"
	FileService_InitPresignedUpload_FullMethodName     = "/api.file.v1.FileService/InitPresignedUpload"
	FileService_ReportUploadedPart_FullMethodName      = "/api.file.v1.FileService/ReportUploadedPart"
	FileService_CompletePresignedUpload_FullMethodName = "/api.file.v1.FileService/CompletePresignedUpload"
	FileService_AbortPresignedUpload_FullMethodName    = "/api.file.v1.FileService/AbortPresignedUpload"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	// Check instant upload and resumable upload
	CheckUpload(ctx context.Context, in *CheckUploadRequest, opts ...grpc.CallOption) (*CheckUploadReply, error)
	// Upload file chunk
	UploadChunk(ctx context.Context, in *UploadChunkRequest, opts ...grpc.CallOption) (*UploadChunkReply, error)
	// Merge file chunks
	MergeChunks(ctx context.Context, in *MergeChunksRequest, opts ...grpc.CallOption) (*MergeChunksReply, error)
	// Get user file list
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesReply, error)
	// Get file download URL
	GetDownloadURL(ctx context.Context, in *GetDownloadURLRequest, opts ...grpc.CallOption) (*GetDownloadURLReply, error)
	// Delete files (move to trash)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileReply, error)
	// Rename file
	RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileReply, error)
	// Create folder
	CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderReply, error)
	// Move files or folders
	MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*MoveFileReply, error)
	// Get trash list
	ListTrash(ctx context.Context, in *ListTrashRequest, opts ...grpc.CallOption) (*ListTrashReply, error)
	// Restore files from trash
	RestoreFile(ctx context.Context, in *RestoreFileRequest, opts ...grpc.CallOption) (*RestoreFileReply, error)
	// Permanently delete files
	PermanentDelete(ctx context.Context, in *PermanentDeleteRequest, opts ...grpc.CallOption) (*PermanentDeleteReply, error)
	// Create share link
	CreateShare(ctx context.Context, in *CreateShareRequest, opts ...grpc.CallOption) (*CreateShareReply, error)
	// Get share content
	GetShare(ctx context.Context, in *GetShareRequest, opts ...grpc.CallOption) (*GetShareReply, error)
	// Search files
	SearchFiles(ctx context.Context, in *SearchFilesRequest, opts ...grpc.CallOption) (*SearchFilesReply, error)
	// Get disk usage
	GetDiskUsage(ctx context.Context, in *GetDiskUsageRequest, opts ...grpc.CallOption) (*GetDiskUsageReply, error)
	// Stream file content (for local-mode downloads)
	StreamFileContent(ctx context.Context, in *StreamFileContentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamFileContentReply], error)
	// Presigned multipart upload: init or resume session
	InitPresignedUpload(ctx context.Context, in *InitPresignedUploadRequest, opts ...grpc.CallOption) (*InitPresignedUploadReply, error)
	// Report a completed part after direct-to-storage upload
	ReportUploadedPart(ctx context.Context, in *ReportUploadedPartRequest, opts ...grpc.CallOption) (*ReportUploadedPartReply, error)
	// Complete presigned multipart upload
	CompletePresignedUpload(ctx context.Context, in *CompletePresignedUploadRequest, opts ...grpc.CallOption) (*CompletePresignedUploadReply, error)
	// Abort presigned multipart upload
	AbortPresignedUpload(ctx context.Context, in *AbortPresignedUploadRequest, opts ...grpc.CallOption) (*AbortPresignedUploadReply, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) CheckUpload(ctx context.Context, in *CheckUploadRequest, opts ...grpc.CallOption) (*CheckUploadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUploadReply)
	err := c.cc.Invoke(ctx, FileService_CheckUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UploadChunk(ctx context.Context, in *UploadChunkRequest, opts ...grpc.CallOption) (*UploadChunkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadChunkReply)
	err := c.cc.Invoke(ctx, FileService_UploadChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) MergeChunks(ctx context.Context, in *MergeChunksRequest, opts ...grpc.CallOption) (*MergeChunksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeChunksReply)
	err := c.cc.Invoke(ctx, FileService_MergeChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesReply)
	err := c.cc.Invoke(ctx, FileService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetDownloadURL(ctx context.Context, in *GetDownloadURLRequest, opts ...grpc.CallOption) (*GetDownloadURLReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDownloadURLReply)
	err := c.cc.Invoke(ctx, FileService_GetDownloadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileReply)
	err := c.cc.Invoke(ctx, FileService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameFileReply)
	err := c.cc.Invoke(ctx, FileService_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFolderReply)
	err := c.cc.Invoke(ctx, FileService_CreateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*MoveFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveFileReply)
	err := c.cc.Invoke(ctx, FileService_MoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ListTrash(ctx context.Context, in *ListTrashRequest, opts ...grpc.CallOption) (*ListTrashReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrashReply)
	err := c.cc.Invoke(ctx, FileService_ListTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) RestoreFile(ctx context.Context, in *RestoreFileRequest, opts ...grpc.CallOption) (*RestoreFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreFileReply)
	err := c.cc.Invoke(ctx, FileService_RestoreFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) PermanentDelete(ctx context.Context, in *PermanentDeleteRequest, opts ...grpc.CallOption) (*PermanentDeleteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermanentDeleteReply)
	err := c.cc.Invoke(ctx, FileService_PermanentDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CreateShare(ctx context.Context, in *CreateShareRequest, opts ...grpc.CallOption) (*CreateShareReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShareReply)
	err := c.cc.Invoke(ctx, FileService_CreateShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetShare(ctx context.Context, in *GetShareRequest, opts ...grpc.CallOption) (*GetShareReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShareReply)
	err := c.cc.Invoke(ctx, FileService_GetShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) SearchFiles(ctx context.Context, in *SearchFilesRequest, opts ...grpc.CallOption) (*SearchFilesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFilesReply)
	err := c.cc.Invoke(ctx, FileService_SearchFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetDiskUsage(ctx context.Context, in *GetDiskUsageRequest, opts ...grpc.CallOption) (*GetDiskUsageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiskUsageReply)
	err := c.cc.Invoke(ctx, FileService_GetDiskUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) StreamFileContent(ctx context.Context, in *StreamFileContentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamFileContentReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[0], FileService_StreamFileContent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFileContentRequest, StreamFileContentReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileService_StreamFileContentClient = grpc.ServerStreamingClient[StreamFileContentReply]

func (c *fileServiceClient) InitPresignedUpload(ctx context.Context, in *InitPresignedUploadRequest, opts ...grpc.CallOption) (*InitPresignedUploadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitPresignedUploadReply)
	err := c.cc.Invoke(ctx, FileService_InitPresignedUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ReportUploadedPart(ctx context.Context, in *ReportUploadedPartRequest, opts ...grpc.CallOption) (*ReportUploadedPartReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportUploadedPartReply)
	err := c.cc.Invoke(ctx, FileService_ReportUploadedPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CompletePresignedUpload(ctx context.Context, in *CompletePresignedUploadRequest, opts ...grpc.CallOption) (*CompletePresignedUploadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletePresignedUploadReply)
	err := c.cc.Invoke(ctx, FileService_CompletePresignedUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) AbortPresignedUpload(ctx context.Context, in *AbortPresignedUploadRequest, opts ...grpc.CallOption) (*AbortPresignedUploadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortPresignedUploadReply)
	err := c.cc.Invoke(ctx, FileService_AbortPresignedUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
type FileServiceServer interface {
	// Check instant upload and resumable upload
	CheckUpload(context.Context, *CheckUploadRequest) (*CheckUploadReply, error)
	// Upload file chunk
	UploadChunk(context.Context, *UploadChunkRequest) (*UploadChunkReply, error)
	// Merge file chunks
	MergeChunks(context.Context, *MergeChunksRequest) (*MergeChunksReply, error)
	// Get user file list
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesReply, error)
	// Get file download URL
	GetDownloadURL(context.Context, *GetDownloadURLRequest) (*GetDownloadURLReply, error)
	// Delete files (move to trash)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileReply, error)
	// Rename file
	RenameFile(context.Context, *RenameFileRequest) (*RenameFileReply, error)
	// Create folder
	CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderReply, error)
	// Move files or folders
	MoveFile(context.Context, *MoveFileRequest) (*MoveFileReply, error)
	// Get trash list
	ListTrash(context.Context, *ListTrashRequest) (*ListTrashReply, error)
	// Restore files from trash
	RestoreFile(context.Context, *RestoreFileRequest) (*RestoreFileReply, error)
	// Permanently delete files
	PermanentDelete(context.Context, *PermanentDeleteRequest) (*PermanentDeleteReply, error)
	// Create share link
	CreateShare(context.Context, *CreateShareRequest) (*CreateShareReply, error)
	// Get share content
	GetShare(context.Context, *GetShareRequest) (*GetShareReply, error)
	// Search files
	SearchFiles(context.Context, *SearchFilesRequest) (*SearchFilesReply, error)
	// Get disk usage
	GetDiskUsage(context.Context, *GetDiskUsageRequest) (*GetDiskUsageReply, error)
	// Stream file content (for local-mode downloads)
	StreamFileContent(*StreamFileContentRequest, grpc.ServerStreamingServer[StreamFileContentReply]) error
	// Presigned multipart upload: init or resume session
	InitPresignedUpload(context.Context, *InitPresignedUploadRequest) (*InitPresignedUploadReply, error)
	// Report a completed part after direct-to-storage upload
	ReportUploadedPart(context.Context, *ReportUploadedPartRequest) (*ReportUploadedPartReply, error)
	// Complete presigned multipart upload
	CompletePresignedUpload(context.Context, *CompletePresignedUploadRequest) (*CompletePresignedUploadReply, error)
	// Abort presigned multipart upload
	AbortPresignedUpload(context.Context, *AbortPresignedUploadRequest) (*AbortPresignedUploadReply, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) CheckUpload(context.Context, *CheckUploadRequest) (*CheckUploadReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUpload not implemented")
}
func (UnimplementedFileServiceServer) UploadChunk(context.Context, *UploadChunkRequest) (*UploadChunkReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadChunk not implemented")
}
func (UnimplementedFileServiceServer) MergeChunks(context.Context, *MergeChunksRequest) (*MergeChunksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeChunks not implemented")
}
func (UnimplementedFileServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedFileServiceServer) GetDownloadURL(context.Context, *GetDownloadURLRequest) (*GetDownloadURLReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDownloadURL not implemented")
}
func (UnimplementedFileServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedFileServiceServer) RenameFile(context.Context, *RenameFileRequest) (*RenameFileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedFileServiceServer) CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedFileServiceServer) MoveFile(context.Context, *MoveFileRequest) (*MoveFileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveFile not implemented")
}
func (UnimplementedFileServiceServer) ListTrash(context.Context, *ListTrashRequest) (*ListTrashReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrash not implemented")
}
func (UnimplementedFileServiceServer) RestoreFile(context.Context, *RestoreFileRequest) (*RestoreFileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreFile not implemented")
}
func (UnimplementedFileServiceServer) PermanentDelete(context.Context, *PermanentDeleteRequest) (*PermanentDeleteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PermanentDelete not implemented")
}
func (UnimplementedFileServiceServer) CreateShare(context.Context, *CreateShareRequest) (*CreateShareReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShare not implemented")
}
func (UnimplementedFileServiceServer) GetShare(context.Context, *GetShareRequest) (*GetShareReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShare not implemented")
}
func (UnimplementedFileServiceServer) SearchFiles(context.Context, *SearchFilesRequest) (*SearchFilesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchFiles not implemented")
}
func (UnimplementedFileServiceServer) GetDiskUsage(context.Context, *GetDiskUsageRequest) (*GetDiskUsageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiskUsage not implemented")
}
func (UnimplementedFileServiceServer) StreamFileContent(*StreamFileContentRequest, grpc.ServerStreamingServer[StreamFileContentReply]) error {
	return status.Error(codes.Unimplemented, "method StreamFileContent not implemented")
}
func (UnimplementedFileServiceServer) InitPresignedUpload(context.Context, *InitPresignedUploadRequest) (*InitPresignedUploadReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InitPresignedUpload not implemented")
}
func (UnimplementedFileServiceServer) ReportUploadedPart(context.Context, *ReportUploadedPartRequest) (*ReportUploadedPartReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUploadedPart not implemented")
}
func (UnimplementedFileServiceServer) CompletePresignedUpload(context.Context, *CompletePresignedUploadRequest) (*CompletePresignedUploadReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CompletePresignedUpload not implemented")
}
func (UnimplementedFileServiceServer) AbortPresignedUpload(context.Context, *AbortPresignedUploadRequest) (*AbortPresignedUploadReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortPresignedUpload not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call panics, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_CheckUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CheckUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CheckUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CheckUpload(ctx, req.(*CheckUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UploadChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UploadChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UploadChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UploadChunk(ctx, req.(*UploadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_MergeChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).MergeChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_MergeChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).MergeChunks(ctx, req.(*MergeChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetDownloadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDownloadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetDownloadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetDownloadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetDownloadURL(ctx, req.(*GetDownloadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).RenameFile(ctx, req.(*RenameFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CreateFolder(ctx, req.(*CreateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_MoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).MoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_MoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).MoveFile(ctx, req.(*MoveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ListTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ListTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ListTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ListTrash(ctx, req.(*ListTrashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_RestoreFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).RestoreFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_RestoreFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).RestoreFile(ctx, req.(*RestoreFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_PermanentDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermanentDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).PermanentDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_PermanentDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).PermanentDelete(ctx, req.(*PermanentDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CreateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CreateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CreateShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CreateShare(ctx, req.(*CreateShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetShare(ctx, req.(*GetShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_SearchFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).SearchFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_SearchFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).SearchFiles(ctx, req.(*SearchFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetDiskUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiskUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetDiskUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetDiskUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetDiskUsage(ctx, req.(*GetDiskUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_StreamFileContent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamFileContentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileServiceServer).StreamFileContent(m, &grpc.GenericServerStream[StreamFileContentRequest, StreamFileContentReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileService_StreamFileContentServer = grpc.ServerStreamingServer[StreamFileContentReply]

func _FileService_InitPresignedUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitPresignedUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).InitPresignedUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_InitPresignedUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).InitPresignedUpload(ctx, req.(*InitPresignedUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ReportUploadedPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportUploadedPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ReportUploadedPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ReportUploadedPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ReportUploadedPart(ctx, req.(*ReportUploadedPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CompletePresignedUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletePresignedUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CompletePresignedUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CompletePresignedUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CompletePresignedUpload(ctx, req.(*CompletePresignedUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_AbortPresignedUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortPresignedUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).AbortPresignedUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_AbortPresignedUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).AbortPresignedUpload(ctx, req.(*AbortPresignedUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.file.v1.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUpload",
			Handler:    _FileService_CheckUpload_Handler,
		},
		{
			MethodName: "UploadChunk",
			Handler:    _FileService_UploadChunk_Handler,
		},
		{
			MethodName: "MergeChunks",
			Handler:    _FileService_MergeChunks_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _FileService_ListFiles_Handler,
		},
		{
			MethodName: "GetDownloadURL",
			Handler:    _FileService_GetDownloadURL_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _FileService_DeleteFile_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _FileService_RenameFile_Handler,
		},
		{
			MethodName: "CreateFolder",
			Handler:    _FileService_CreateFolder_Handler,
		},
		{
			MethodName: "MoveFile",
			Handler:    _FileService_MoveFile_Handler,
		},
		{
			MethodName: "ListTrash",
			Handler:    _FileService_ListTrash_Handler,
		},
		{
			MethodName: "RestoreFile",
			Handler:    _FileService_RestoreFile_Handler,
		},
		{
			MethodName: "PermanentDelete",
			Handler:    _FileService_PermanentDelete_Handler,
		},
		{
			MethodName: "CreateShare",
			Handler:    _FileService_CreateShare_Handler,
		},
		{
			MethodName: "GetShare",
			Handler:    _FileService_GetShare_Handler,
		},
		{
			MethodName: "SearchFiles",
			Handler:    _FileService_SearchFiles_Handler,
		},
		{
			MethodName: "GetDiskUsage",
			Handler:    _FileService_GetDiskUsage_Handler,
		},
		{
			MethodName: "InitPresignedUpload",
			Handler:    _FileService_InitPresignedUpload_Handler,
		},
		{
			MethodName: "ReportUploadedPart",
			Handler:    _FileService_ReportUploadedPart_Handler,
		},
		{
			MethodName: "CompletePresignedUpload",
			Handler:    _FileService_CompletePresignedUpload_Handler,
		},
		{
			MethodName: "AbortPresignedUpload",
			Handler:    _FileService_AbortPresignedUpload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFileContent",
			Handler:       _FileService_StreamFileContent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "file/v1/file.proto",
}
