// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/J-Y-Zhang/light-cloud-disk/internal/biz"
	"github.com/J-Y-Zhang/light-cloud-disk/internal/conf"
	"github.com/J-Y-Zhang/light-cloud-disk/internal/data"
	"github.com/J-Y-Zhang/light-cloud-disk/internal/server"
	"github.com/J-Y-Zhang/light-cloud-disk/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, logger)
	fileRepo := data.NewFileRepo(dataData, logger)
	fileUsecase := biz.NewFileUsecase(fileRepo, userRepo, logger)
	fileService := service.NewFileService(fileUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, userService, fileService, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, fileService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
